### ISSUE TITLE
Module name

### ISSUE THREAD

**Issue by rehno-lindeque** [mgold/elm-date-format#2]
I just noticed that @heyLu forked this package, renaming `Elm-Format-String` to `elm-format-date` and `FormatString` to `FormatDate` for the module name.

I'd propose `elm-date-format` and `Date.Format` myself for uniformity (at least, this is how circuithub modules look). This way it lines up nicely with say 
```
-- Other (potential) date packages
elm-date-extra         Date.Extra
elm-date-conversion    Date.Convert
elm-date-format        Date.Format
elm-date-format-extra  Date.Format.Extra

-- Other (potential) formatting packages
elm-number-format      Number.Format

-- Existing core libraries
core                   Json.Decode
core                   Json.Encode
```

I only thought I'd mention it since this strange fork now exists, I'm not massively concerned by naming conventions!

**Comment by mgold** [comment]
I'm all for consistency, and I'm honestly unsure what prompted the fork - I'm happy to take contributions, etc., if it means one really awesome library instead of two sucky ones. As for the rename, I'm not sure if elm-package will let me do that, but it sounds reasonable.

**Comment by heyLu** [comment]
Ah sorry, that fork was just to get some code of mine working. I think this library doesn't work with recent versions of elm, because the module is stored in a file with a lower-case name. Renaming `formatString.elm` to `FormatString.elm` made it work.

(The remaining changes were just playing around, although I *do* think the suggested new name and module path are better.)

**Comment by rehno-lindeque** [comment]
I guess @evan will implement renames at some point :)

**Comment by mgold** [comment]
@heyLu Sorry for the trouble. Are you building from source, because 0.14.1 doesn't seem to have an issue with the lowercase filename.

Anyway, I've made @rehno-lindeque's suggested changes, though not released them yet. Please review and comment, or send a PR. If you think it looks good I'll tag the commit.

**Comment by heyLu** [comment]
@mgold No problem, thanks for writing the module! :)

I had a quick look, apart from the `@docs` thing [I commented on](https://github.com/mgold/elm-date-format/commit/e12a14bbe590be70d1ad298a813184a8d93aeff8#commitcomment-10115469) everything looks good!

**Comment by mgold** [comment]
`@docs` has been fixed. Now, I'm just torn about whether 2.0.0 should wait for 0.15 or not.

**Comment by mgold** [comment]
@heyLu @rehno-lindeque I've pushed up a commit for 0.15 and the new version of elm-test. Anything else to consider before releasing?

**Comment by rehno-lindeque** [comment]
Those changes look pretty ok to me. Thanks for the update!

**Comment by mgold** [comment]
Great, we're all set.
